### PR TITLE
2.9.6 released

### PR DESCRIPTION
**Pull request by smathot**
Hi Daniel,

A heads-up that I just tagged 2.9.6 for release. Could you package it for Mac OS?

Cheers!
Sebastiaan

### CODE REVIEW

**Comment by dschreij** [comment]
Will do!

**Comment by dschreij** [comment]
Ok, I have put the new version at the previous location. I'll update the documentation soon, or maybe you can do that with the next change you make (the only thing that needs to be updated is the version number of the file, and the version that is mentioned on the dockage).

**Comment by smathot** [comment]
Great! What is the feedback so far on the Mac OS package? I'm asking because we could change the Mac-OS link on the downloads page to a direct download link, instead of pointing towards the paragraph about experimental Mac OS support.

**Comment by dschreij** [comment]
I don't get a lot of negative feedback (and no news is good news I guess...), and the negative feedback that is there, seems to have incidental causes (not enough disk space maybe, or really something to do with peculiarities of the system that OpenSesame is run on). I haven't heard anything at least that isn't known or indicates a structural mistake in OpenSesame

**Pull request merged**
